theme: jekyll-theme-minimal
title: [Tony Alexander Hild]
description: [Dad & husband. Full-stack lazy dev hacker. DIY computer scientist. Researcher. Woodworker. Learning R. C#.]
logo: [images/avatar.jpeg]
