#theme             : jekyll-theme-minimal
remote_theme      : "mmistakes/minimal-mistakes@4.23.0"
title             : "Tony Alexander Hild"
description       : "Dad & husband. Full-stack lazy dev hacker. DIY computer scientist. Researcher. Woodworker. Learning R. C#."
logo              : "images/avatar.jpeg"
show_downloads    : "false"
plugins           : ["jekyll-include-cache"]
